baseURL = "https://mckoss.com/"
languageCode = "en-us"
title = "mckoss.com | Mike Koss"
theme = "hugo-cards"
paginate = 6
publishDir = "docs"
summaryLength = 30

[params]
builtBy = "Mike Koss"
defaultImage = "mike-closeup.jpg"

custom_css = ["css/custom.css"]

twitter = "https://twitter.com/mckoss"
instagram = "https://instagram.com/mckoss"
github = "https://github.com/mckoss"
email = "mike@mckoss.com"
disqus = "mckoss"

analytics = "UA-177353-1"

[params.copyright]
name = "Mike Koss"
link = "https://mckoss.com"
